"""3D-LMM discrete hyperchaotic map from paper Eq. (1)."""

from __future__ import annotations

from dataclasses import dataclass
import math

import numpy as np

from .config import LMMParameters


@dataclass(frozen=True)
class ChaoticSequences:
    """Three state sequences generated by the 3D-LMM recurrence."""

    x: np.ndarray
    y: np.ndarray
    z: np.ndarray


def lmm_step(x: float, y: float, z: float, p: LMMParameters) -> tuple[float, float, float]:
    """Advance the proposed 3D-LMM by one iteration (paper Eq. (1))."""

    xn = p.a * ((p.c + p.d * math.cos(x * (1.0 - x))) + (p.e + p.b * math.sin(math.pi * z)) + 1.0)
    yn = p.a * ((p.c + p.d * math.cos(y * (1.0 - y))) + (p.e + p.b * math.sin(math.pi * x)) + 1.0)
    zn = p.a * ((p.c + p.d * math.cos(z * (1.0 - z))) + (p.e + p.b * math.sin(math.pi * y)) + 1.0)
    return xn, yn, zn


def generate_3d_lmm(
    length: int,
    *,
    x0: float,
    y0: float,
    z0: float,
    params: LMMParameters,
) -> ChaoticSequences:
    """Generate ``length`` states, including the supplied state as n=0.

    MATLAB uses IEEE-754 double precision by default; Python floats and the
    NumPy arrays used here are also binary64, which is the closest open-source
    numerical analogue for the recurrence itself.
    """

    if length <= 0:
        raise ValueError("length must be positive")
    x = np.empty(length, dtype=np.float64)
    y = np.empty(length, dtype=np.float64)
    z = np.empty(length, dtype=np.float64)
    x[0], y[0], z[0] = x0, y0, z0
    for i in range(1, length):
        x[i], y[i], z[i] = lmm_step(x[i - 1], y[i - 1], z[i - 1], params)
    return ChaoticSequences(x=x, y=y, z=z)


def sequence_length_for_image(height: int, width: int, *, sbox_index_burnin: int) -> int:
    """Conservative sequence length for S-box, XOR and FQM operations.

    FQM filters its driving sequence to even residues (paper Eq. (10)); using
    roughly 2x the pixel count provides ample candidates while keeping the
    implementation deterministic.  ``cipher.py`` extends the sequence if an
    unusually biased realization does not provide enough even residues.
    """

    pixels = height * width
    return max(sbox_index_burnin + 4096, 2 * pixels + 1024)
